project:
  type: website
  output-dir: docs

website:
  title: "SheBoom"
  repo-url: https://github.com/SheBoom/SheBoom.github.io
  image: /images/logo.png
  favicon: /images/favicon.ico
  open-graph: true
  description: "Welcome to SheBoom, reputedly Europe’s largest women’s drumming ensemble based in Glasgow, Scotland. SheBoom is an unforgettably dynamic percussion band playing a uniquely infectious mix of afro-brazilian, samba, african, latin, celtic and european rhythms."
  navbar:
    logo: /images/logo.png
    logo-alt: "A purple butterfly with a face pattern"
    right:
      - text: About
        menu: 
          - about.qmd
      - icon: facebook
        href: https://www.facebook.com/SheBoomDrums/
format:
  html:
    theme: slate
    css: styles.css



