---
title: Herstory
---

SheBoom grew out of the percussion performance in the spectacular artwork: Keltic Clyde Firewitch – designed and directed by Jane Sutherland and brought to life under the musical direction of Erin Scrutton. Jane and Erin first collaborated planning a Reclaim the Night March in 1989.

The Firewitch Project was created for the very first Glasgay! in 1993, a pyrotechnic performance on the Clyde’s old Suspension Bridge at the Witching Time of Samhuinn, passionately engaging the creative efforts of more than 120 women (AND a few men of goodwill).  Following the success of this event, the women wouldn’t put down their sticks, and other gigs were played in the Glasgay! Festival.  It wasn’t until later on that a band member “coined the term ‘SheBoom’ which seemed to capture the phenomenon of women drumming”.  We are one of the first, and were certainly the biggest, all-women drumming bands in Europe and celebrate our 30th birthday in 2023.  SheBoom is, we think, Glasgay's! most enduring and culturally significant sensation.

Over the years, hundreds of women have been members of SheBoom. We play at marches and protests all across the UK and beyond. SheBoom has played a wide variety of venues ranging from the Royal Albert Hall in London to Drumchapel Shopping Centre and led many marches including those frequently organised by Pride, Reclaim the Night, Scottish Parliament, STUC, CND, Anti-Racism, Women’s Aid, Rape Crisis.  We have also been part of the Correfoc in Barcelona and more recently SheBoom have played at the International Women’s Festival, Lesvos, as well as several of the Glasgow-based Olympic and Commonwealth events, and the Women of the World Festival
